name: ci

on:
  push:
    branches: master

jobs:
  build_amd64:
    name: Build & push amd64 image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./amd64.Dockerfile
          push: true
          tags: |
            skyraptor/btcpayserver:latest
            skyraptor/btcpayserver:amd64-latest
            skyraptor/btcpayserver:${{ env.GITHUB_RUN_ID }}
            skyraptor/btcpayserver:amd64-${{ env.GITHUB_RUN_ID }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  build_arm32v7:
    name: Build & push arm32v7 image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./arm32v7.Dockerfile
          push: true
          tags: |
            skyraptor/btcpayserver:arm32v7-latest
            skyraptor/btcpayserver:arm32v7-${{ env.GITHUB_RUN_ID }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  build_arm64v8:
    name: Build & push arm64v8 image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./arm64v8.Dockerfile
          push: true
          tags: |
            skyraptor/btcpayserver:arm64v8-latest
            skyraptor/btcpayserver:arm64v8-${{ env.GITHUB_RUN_ID }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
